#!/usr/bin/env bash
set -e

sessions="admin bigcartel checkout hub"

# avoid tmux failed to connect messages with a temporary session
tmux new-session -ds temporary-session

for session in $sessions; do
  if [ `tmux ls | grep $session | wc -l` -eq 0 ]; then
    echo "Setting up session $session."
    setup_session $session
  else
    echo "Session $session already exists. Skipping."
  fi
done

# clean up temporary session
tmux kill-session -t temporary-session

echo "Done!"
