#!/usr/bin/env bash
set -e

pair=$1

first=$(echo $USER$'\n'$pair | sort | tr '\n' ' ' | awk '{print $1;}')
last=$(echo $USER$'\n'$pair | sort | tr '\n' ' ' | awk '{print $2;}')

open https://plus.google.com/hangouts/_/bigcartel.com/$first-$last
